/*
 * Copyright (c) 2014-2019 - uPmem
 */

#ifndef DPU_POC_MRAM_STRUCTURE_H
#define DPU_POC_MRAM_STRUCTURE_H

#include <stdint.h>

#define QUERY_BUFFER_OFFSET 0
#define QUERY_BUFFER_SIZE 16

#define FILES_SUMMARY_BUFFER_OFFSET QUERY_BUFFER_OFFSET + QUERY_BUFFER_SIZE
#define FILES_SUMMARY_BUFFER_SIZE 16


#endif //DPU_POC_MRAM_STRUCTURE_H
